export const COUNTRIES: { name: string; dial: string; flag: string }[] = [
  { name: "Pakistan", dial: "+92", flag: "🇵🇰" },
  { name: "United States", dial: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", dial: "+44", flag: "🇬🇧" },
  { name: "India", dial: "+91", flag: "🇮🇳" },
  { name: "China", dial: "+86", flag: "🇨🇳" },
  { name: "United Arab Emirates", dial: "+971", flag: "🇦🇪" },
  { name: "Saudi Arabia", dial: "+966", flag: "🇸🇦" },
  { name: "Turkey", dial: "+90", flag: "🇹🇷" },
  { name: "Germany", dial: "+49", flag: "🇩🇪" },
  { name: "France", dial: "+33", flag: "🇫🇷" },
  { name: "Spain", dial: "+34", flag: "🇪🇸" },
  { name: "Italy", dial: "+39", flag: "🇮🇹" },
  { name: "Brazil", dial: "+55", flag: "🇧🇷" },
  { name: "Indonesia", dial: "+62", flag: "🇮🇩" },
  { name: "Bangladesh", dial: "+880", flag: "🇧🇩" },
  { name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { name: "Egypt", dial: "+20", flag: "🇪🇬" },
  { name: "Russia", dial: "+7", flag: "🇷🇺" },
  { name: "Japan", dial: "+81", flag: "🇯🇵" },
  { name: "South Korea", dial: "+82", flag: "🇰🇷" },
  { name: "Australia", dial: "+61", flag: "🇦🇺" },
  { name: "Canada", dial: "+1", flag: "🇨🇦" },
  { name: "Mexico", dial: "+52", flag: "🇲🇽" },
  { name: "South Africa", dial: "+27", flag: "🇿🇦" },
  { name: "Malaysia", dial: "+60", flag: "🇲🇾" },
  { name: "Philippines", dial: "+63", flag: "🇵🇭" },
  { name: "Singapore", dial: "+65", flag: "🇸🇬" },
  { name: "Thailand", dial: "+66", flag: "🇹🇭" },
  { name: "Vietnam", dial: "+84", flag: "🇻🇳" },
  { name: "Netherlands", dial: "+31", flag: "🇳🇱" },
];
